version: '3'
services:
  mapploter_php_dev:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mapplotter_dev
    image: refeed/mapplotter:latest
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - mysql
    networks:
      - backend
    volumes:
      - ./src:/var/www/html/

  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_HOST: '%'
      MYSQL_ROOT_PASSWORD: "verybigsecret"
    ports:
      - "3306:3306"
    volumes:
      - ./db/mapploter.sql:/docker-entrypoint-initdb.d/mapploter.sql
      - mysqldata:/var/lib/mysql
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  mysqldata:
    driver: local
