CREATE DATABASE IF NOT EXISTS Mapplotter;

USE Mapplotter;

CREATE TABLE IF NOT EXISTS Mission (
    id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    missionName VARCHAR(255) NOT NULL,
    geoJSON LONGTEXT NOT NULL,
    createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);
